# Generated by Django 2.1.7 on 2019-04-10 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.TextField(default='Jane Doe')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('personal_message', models.TextField(default='I am excited to meet you')),
                ('matchedMateID', models.PositiveIntegerField(default=0)),
                ('matchedMatePName', models.TextField(default='John Doe')),
                ('matchedMateImage', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('matchedMatePMessage', models.TextField(default='Meet me please!!!')),
                ('matchedMatePEmail', models.TextField(default='johndoe@gmail.com')),
                ('matchedMatePEmailb', models.TextField(default='johndoe@gmail.com')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
