# Generated by Django 2.1.7 on 2019-04-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(default='I am excited to meet you'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.TextField(default='Jane Doe'),
        ),
    ]
