# Generated by Django 2.1.7 on 2019-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190414_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.TextField(default='Jane Doe', max_length=50),
        ),
    ]
