# Generated by Django 2.1.7 on 2019-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190414_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='match_mate_ID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_message',
            field=models.CharField(default='I am excited to meet you!!', max_length=50),
        ),
    ]
