# Generated by Django 2.1.7 on 2019-04-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190414_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_message',
            field=models.CharField(default='Hello!', max_length=50),
        ),
    ]
