# Generated by Django 2.1.7 on 2019-04-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190414_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_message',
            field=models.TextField(default='Hello!'),
        ),
    ]
