# Generated by Django 2.1.7 on 2019-04-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_matched',
            field=models.BooleanField(default=True),
        ),
    ]
