# Generated by Django 2.1.7 on 2019-04-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190414_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signed_in',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
