# Generated by Django 2.1.7 on 2019-04-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190414_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_matched',
            field=models.BooleanField(default=True),
        ),
    ]
