# Generated by Django 2.1.7 on 2019-04-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190414_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_matched',
            new_name='signed_in',
        ),
    ]
