# Generated by Django 2.1.7 on 2019-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_is_matched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='match_mate_ID',
            new_name='mate_ID',
        ),
        migrations.AddField(
            model_name='profile',
            name='mate_email',
            field=models.TextField(default='johndoe@gmail.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mate_firstname',
            field=models.CharField(default='Christoper', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='mate_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mate_lastname',
            field=models.CharField(default='Eisgruber', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='mate_personal_message',
            field=models.TextField(default='Hello!'),
        ),
    ]
