# Generated by Django 2.1.7 on 2019-04-17 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190414_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mate_email',
            field=models.TextField(default='princeton@princeton.edu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
