# Generated by Django 2.1.7 on 2019-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190417_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_customized',
            field=models.BooleanField(default=False),
        ),
    ]
