# Generated by Django 2.1.7 on 2019-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_has_customized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mate_email',
            field=models.CharField(default='princeton@princeton.edu', max_length=50),
        ),
    ]
