# Generated by Django 2.1.7 on 2019-05-01 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190501_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pref1',
        ),
        migrations.AddField(
            model_name='profile',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
