# Generated by Django 2.1.7 on 2019-05-01 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190501_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qty',
        ),
        migrations.AddField(
            model_name='profile',
            name='pref1',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
