# Generated by Django 2.1.7 on 2019-05-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190508_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_matched',
            new_name='is_global',
        ),
    ]
