# Generated by Django 2.1.7 on 2019-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190509_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
