# Generated by Django 2.1.7 on 2019-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_profile_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
