# Generated by Django 2.1.7 on 2019-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_is_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wants_group',
            field=models.BooleanField(default=True),
        ),
    ]
