# Generated by Django 2.1.7 on 2019-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_wants_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
