# Generated by Django 2.1.7 on 2019-04-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
