# Generated by Django 2.1.7 on 2019-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
