# Generated by Django 2.1.7 on 2019-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_remove_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='group_description',
        ),
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='default.jpg', upload_to='group_pics'),
        ),
    ]
