# Generated by Django 2.1.7 on 2019-04-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20190423_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
