# Generated by Django 2.1.7 on 2019-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190421_0714'),
        ('match', '0007_auto_20190424_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
