# Generated by Django 2.1.7 on 2019-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_id', models.PositiveIntegerField(default=0)),
                ('p2_id', models.PositiveIntegerField(default=0)),
                ('group_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_pairs',
            field=models.ManyToManyField(to='match.Pair'),
        ),
    ]
