# Generated by Django 2.1.7 on 2019-04-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20190424_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='p1_id',
            new_name='pair_1',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='p2_id',
            new_name='pair_2',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_pairs',
        ),
        migrations.AddField(
            model_name='group',
            name='group_pairs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='match.Pair'),
            preserve_default=False,
        ),
    ]
