# Generated by Django 2.1.7 on 2019-04-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20190424_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_pairs',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='group_id',
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Group'),
        ),
    ]
