# Generated by Django 2.1.7 on 2019-05-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_auto_20190508_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='pair1_pMessage',
            field=models.TextField(default='Hello!'),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair2_pMessage',
            field=models.TextField(default='Hello!'),
        ),
    ]
