# Generated by Django 2.1.7 on 2019-05-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0018_auto_20190511_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='pair1_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='pair2_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
