# Generated by Django 2.1.7 on 2019-05-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0019_auto_20190512_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='default.jpg', upload_to='group_pics'),
        ),
    ]
